pages:
  stage: deploy
  script:
    - /home/miniconda3/julia-1.5.2/bin/julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.add("CUDA")'
    - /home/miniconda3/julia-1.5.2/bin/julia --project make.jl  # make slides
    - /home/miniconda3/julia-1.5.2/bin/julia --project generate_nb.jl  # make notebooks
    - mv docs/build public  # move slides to the directory picked up by Gitlab pages
    - mv notebooks public  # move notebooks to the directory picked up by Gitlab pages

  artifacts:
    paths:
      - public
  only:
    - master
