pages:
  stage: deploy
  script:
    - /opt/julia-1.2.0/bin/julia --color=yes make.jl  # make slides
    - mv docs/build public  # move to the directory picked up by Gitlab pages
  artifacts:
    paths:
      - public
  only:
    - master