pages:
  stage: deploy
  script:
    - /opt/julia-1.3.1/bin/julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.add("CuArrays")'
    - /opt/julia-1.3.1/bin/julia --project make.jl  # make slides
    - mv docs/build public  # move to the directory picked up by Gitlab pages
  artifacts:
    paths:
      - public
  only:
    - master
