pages:
  stage: deploy
  script:
    - env CUDA_ROOT=/usr/local/cuda-9.0 /opt/julia-1.2.0/bin/julia --project -e 'using Pkg; Pkg.instantiate()'
    - env CUDA_ROOT=/usr/local/cuda-9.0 /opt/julia-1.2.0/bin/julia --project --color=yes make.jl  # make slides
    - mv docs/build public  # move to the directory picked up by Gitlab pages
  artifacts:
    paths:
      - public
  only:
    - master