pages:
  image: julia:1.3
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y git 
    - julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.dev("Remark");'
    - julia --color=yes make.jl  # make slides
    - mv docs/build public  # move to the directory picked up by Gitlab pages
  artifacts:
    paths:
      - public
  only:
    - master